[package]
name = "call"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
rand = "0.8.4"
